"""
Forensic Specialist Writer Agent — Obscuro Deepimage.

Generates professional, court-grade forensic analysis reports from detection verdicts.
Writes in the style of a senior digital forensics examiner:
  - Case identification and chain of digital evidence
  - Examination methodology
  - Per-signal technical findings with forensic interpretation
  - Statistical confidence assessment
  - Expert opinion and verdict justification
  - Limitations, caveats, and recommendations

No external LLM required — uses a structured, context-aware generation engine
that produces varied, professional prose from signal data.
"""
import logging
import hashlib
import random
import textwrap
from datetime import datetime, timezone
from typing import Optional

from app.schemas import AgentResult, ForensicVerdict

logger = logging.getLogger(__name__)


# ─── Case numbering ───────────────────────────────────────────────────────────

def _make_case_id(input_hash: str) -> str:
    h = input_hash[:8].upper() if input_hash else "UNKNOWN"
    now = datetime.now(timezone.utc)
    return f"ODF-{now.strftime('%Y%m%d')}-{h}"


# ─── Narrative templates ──────────────────────────────────────────────────────

_HEADER_TEMPLATES = [
    "Upon forensic examination of the submitted digital media, the following analysis was conducted "
    "using the Obscuro Deepimage multi-agent detection framework.",

    "This report documents the findings of a systematic forensic examination performed on the "
    "submitted digital media artifact using the Obscuro Deepimage agentic analysis pipeline.",

    "The following constitutes a formal digital forensic examination report generated by the "
    "Obscuro Deepimage system upon analysis of the submitted media sample.",
]

_FAKE_VERDICTS = [
    (
        "Based on the convergent evidence from multiple independent forensic signals, it is the "
        "conclusion of this examination that the submitted media exhibits characteristics "
        "**strongly consistent with synthetic or AI-generated content**. The weight of forensic "
        "evidence points toward deliberate fabrication."
    ),
    (
        "The cumulative forensic evidence gathered through multi-agent signal analysis leads to "
        "the determination that the submitted media is **likely of synthetic origin**. Multiple "
        "detection modalities corroborate this finding with above-threshold confidence."
    ),
    (
        "Having applied a battery of independent forensic analyses to the submitted digital artifact, "
        "this examiner concludes that the media **bears hallmarks of deepfake generation**. "
        "The composite signal profile is inconsistent with naturally-captured media."
    ),
]

_REAL_VERDICTS = [
    (
        "The forensic examination of the submitted media did not reveal patterns characteristic of "
        "known synthetic generation methods. The evidence is **consistent with authentic, unmanipulated "
        "media**. However, this finding does not constitute an absolute certificate of authenticity."
    ),
    (
        "Upon systematic analysis across multiple forensic detection modalities, no significant "
        "indicators of synthetic origin were identified. The submitted media **appears consistent "
        "with genuine, unaltered content** within the detection capabilities of this system."
    ),
    (
        "The multi-agent forensic analysis returned findings broadly compatible with authentic media. "
        "Absent compelling indicators of manipulation, this examination concludes that the media is "
        "**likely genuine** — though adversarially crafted content may evade current detection methods."
    ),
]

_UNCERTAIN_VERDICTS = [
    (
        "The forensic evidence yielded an **inconclusive result**. Individual detection signals "
        "produced contradictory findings, and the aggregate confidence falls below the threshold "
        "required for a definitive determination. **Manual expert review is strongly recommended.**"
    ),
    (
        "The signal profile of this media sample is ambiguous. Detection modalities disagree, "
        "and no single dominant pattern emerged. This examination is **unable to issue a reliable "
        "verdict** without additional evidence or a higher-resolution sample."
    ),
    (
        "After comprehensive multi-signal analysis, the forensic evidence remains **equivocal**. "
        "The probability distribution straddles the decision boundary, indicating either a borderline "
        "case, adversarial evasion, or a media type underrepresented in the training distribution."
    ),
]

_SPATIAL_INTERPRETATIONS = {
    "high_fake": [
        "Pixel-level forensic examination revealed anomalous texture gradients and blending "
        "artifacts inconsistent with natural image formation processes. The ViT-based classifier "
        "detected feature distributions characteristic of GAN or diffusion-model synthesis. "
        "Spatial inconsistencies were observed in {detail_note}.",
        "The spatial forensics agent identified significant departure from expected natural image "
        "statistics. Texture seam artifacts, unnatural smoothing patterns, and pixel distribution "
        "anomalies — hallmarks of neural synthesis — were detected. Confidence in the synthetic "
        "classification is high, supported by an EfficientNet-B4 secondary analysis.",
    ],
    "low_fake": [
        "Pixel-level analysis found no compelling spatial artifacts indicative of synthesis. "
        "The image formation statistics are broadly consistent with authentic photography. "
        "Neither the ViT classifier nor the EfficientNet secondary pathway flagged anomalous "
        "texture patterns at the detection threshold.",
        "Spatial forensic examination found the image's pixel-level statistics to be within "
        "the expected range for authentic media. No blending boundaries, unnatural texture "
        "smoothing, or synthesis artifacts were identified at current detection sensitivity.",
    ],
    "neutral": [
        "Spatial analysis returned a borderline score. Some textural irregularities were noted, "
        "but these are insufficient on their own to conclude synthesis. Compression artifacts, "
        "low resolution, or unusual capture conditions may be contributing factors.",
    ]
}

_FREQUENCY_INTERPRETATIONS = {
    "high_fake": [
        "Frequency-domain analysis of the FFT spectrum revealed spectral fingerprints "
        "consistent with GAN upsampling — periodic peaks at regular spatial frequencies "
        "not typically present in natural imaging. Additionally, channel cross-correlation "
        "analysis flagged mid-frequency patterns associated with diffusion-model artifacts "
        "(per Corvi et al., 2023).",
        "The DCT energy distribution deviated significantly from the Laplacian profile "
        "expected in authentic JPEG-encoded imagery. Anomalous spectral energy concentrations "
        "were identified, consistent with spectral fingerprints left by known synthetic "
        "generation pipelines.",
    ],
    "low_fake": [
        "The spectral analysis of this media shows frequency distributions consistent with "
        "natural image statistics. No GAN upsampling artifacts or anomalous DCT coefficient "
        "distributions were detected. The FFT spectrum did not exhibit the periodic peaks "
        "characteristic of synthetic upsampling.",
        "Frequency-domain examination found no spectral anomalies. The image's FFT power "
        "spectrum follows the expected 1/f^2 roll-off characteristic of natural imagery, "
        "and DCT coefficient distributions are within normal parameters.",
    ],
    "neutral": [
        "The frequency analysis yielded marginal scores. While some spectral irregularities "
        "were noted, these could be attributable to compression, transcoding, or platform "
        "processing rather than synthesis artifacts per se.",
    ]
}

_TEMPORAL_INTERPRETATIONS = {
    "ran_high_fake": [
        "Frame-by-frame optical flow analysis revealed inconsistent motion fields, suggesting "
        "frame-level blending or warping at facial boundaries. Additionally, abnormal blink "
        "rate or absence of natural micro-movements was detected — a known signature of "
        "face-swap deepfakes (Li et al., CVPR 2018). Inter-frame texture variance showed "
        "step discontinuities inconsistent with natural video.",
        "Temporal consistency analysis flagged significant frame-to-frame instability at "
        "presumed face-swap blending boundaries. The optical flow vectors showed directional "
        "anomalies and magnitude spikes not accounted for by natural subject movement. "
        "This pattern is characteristic of face-swap or face-reenactment manipulation.",
    ],
    "ran_low_fake": [
        "Temporal analysis across video frames found motion consistency patterns compatible "
        "with authentic, unmanipulated footage. Optical flow fields were smooth, blink rates "
        "fell within normal human ranges, and inter-frame texture variance showed no "
        "anomalous discontinuities.",
        "Frame-sequence analysis revealed no temporal artifacts. The video's optical flow, "
        "blink cadence, and frame-to-frame texture statistics are consistent with "
        "naturally-captured video content.",
    ],
    "skipped": [
        "Temporal consistency analysis was not performed — this signal requires video input "
        "with a sufficient frame sequence (minimum 8 frames).",
    ]
}

_BIOLOGICAL_INTERPRETATIONS = {
    "ran_high_fake": [
        "Remote photoplethysmography (rPPG) analysis of the facial region failed to detect "
        "a coherent physiological heartbeat signal. Authentic video of a living person "
        "typically exhibits subtle, periodic chrominance variation in skin-tone regions "
        "corresponding to the cardiac cycle. The absence of this signal is forensically "
        "significant and consistent with a synthetic face.",
        "Biological signal analysis (CHROM rPPG) found no plausible heartbeat periodicity "
        "in the facial chrominance data. Real human faces exhibit measurable pulsatile "
        "chrominance modulation (HR 40-200 BPM). Its absence suggests the facial region "
        "may be synthetically rendered rather than captured from a living subject.",
    ],
    "ran_low_fake": [
        "rPPG analysis detected a coherent physiological signal consistent with a natural "
        "human heartbeat in the facial region. This is evidence that the face is captured "
        "from a living subject, which is inconsistent with most current deepfake generation "
        "methods that lack physiological signal modelling.",
        "Biological signal analysis identified pulsatile chrominance modulation in the "
        "expected frequency band, consistent with a live human cardiac cycle. This is a "
        "positive indicator of authentic footage.",
    ],
    "skipped": [
        "Biological signal (rPPG) analysis requires video input with sufficient duration "
        "and frame rate. This signal was not applicable to the submitted sample.",
    ]
}

_LIP_SYNC_INTERPRETATIONS = {
    "ran_high_fake": [
        "Audio-visual synchronisation analysis detected a measurable desynchronisation "
        "between lip articulation patterns and the speech audio track. In authentic "
        "speech video, lip landmark displacement is causally coupled to audio amplitude "
        "and phoneme timing. The observed mismatch is consistent with audio-driven face "
        "animation (lip-sync deepfake) or post-production audio dubbing.",
        "Cross-modal synchrony analysis found significant temporal misalignment between "
        "detected lip movements and the audio waveform. The cross-correlation peak was "
        "outside expected bounds for authentic speech production, suggesting artificial "
        "face animation driven by a separate audio signal.",
    ],
    "ran_low_fake": [
        "Lip-sync analysis found no significant audio-visual desynchronisation. Lip "
        "landmark displacement tracked closely with audio amplitude modulation within "
        "acceptable bounds for authentic speech.",
        "Audio-visual synchrony checks showed consistent coupling between lip movement "
        "and speech audio, consistent with authentic video of a real speaker.",
    ],
    "skipped": [
        "Audio-visual synchronisation analysis requires video with an audio track. "
        "This signal was not applicable to the submitted sample.",
    ]
}

# ─── Section generators ───────────────────────────────────────────────────────

def _get_score_bucket(score: float) -> str:
    if score >= 0.6:
        return "high_fake"
    elif score <= 0.4:
        return "low_fake"
    else:
        return "neutral"


def _get_temporal_bucket(ran: bool, score: float) -> str:
    if not ran:
        return "skipped"
    return "ran_high_fake" if score >= 0.55 else "ran_low_fake"


def _build_executive_summary(
    verdict: str,
    prob: float,
    conf: float,
    media_type: str,
    case_id: str,
    filename: str,
    rng: random.Random,
) -> str:
    header = rng.choice(_HEADER_TEMPLATES)
    if verdict == "LIKELY FAKE":
        conclusion = rng.choice(_FAKE_VERDICTS)
    elif verdict == "LIKELY REAL":
        conclusion = rng.choice(_REAL_VERDICTS)
    else:
        conclusion = rng.choice(_UNCERTAIN_VERDICTS)

    return f"""\
## EXECUTIVE SUMMARY

{header}

**Case Reference:** `{case_id}`
**Media Type:** {media_type.capitalize()}
**Sample:** `{filename}`
**Analysis Timestamp:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}

**Deepfake Probability:** {prob:.1%}  
**Verdict Confidence:** {conf:.0%}  
**Verdict:** **{verdict}**

{conclusion}
"""


def _build_methodology() -> str:
    return """\
## EXAMINATION METHODOLOGY

This examination employed the **Obscuro Deepimage** multi-agent forensic pipeline, comprising:

| Agent | Method | Domain |
|---|---|---|
| Spatial Forensics | ViT (dima806 HF) + EfficientNet-B4 | Pixel/texture artifacts |
| Frequency Analysis | FFT spectral peaks + DCT distribution + channel cross-correlation | Spectral fingerprints |
| Temporal Consistency | Optical flow analysis + blink rate estimation | Frame-level coherence (video) |
| Biological Signal | CHROM rPPG heartbeat detection | Physiological authenticity (video) |
| Audio-Visual Sync | Lip-landmark–audio cross-correlation | Modality coherence (video+audio) |
| Fusion Agent | Confidence-weighted ensemble + quantum-inspired calibration | Signal integration |

All agents operate independently. Their scores are fused using a confidence-weighted ensemble 
with optional variational quantum circuit weight calibration (PennyLane, classical simulation).
No single agent's verdict is treated as conclusive; convergent multi-signal evidence drives the final determination.
"""


def _build_signal_findings(
    agent_results: list,
    fusion_weights: dict,
    rng: random.Random,
) -> str:
    lines = ["## FORENSIC SIGNAL FINDINGS\n"]

    signal_interp = {
        "pixel_artifact_score": (_SPATIAL_INTERPRETATIONS, "### 🖼️ Signal 1: Spatial Forensics (Pixel-Level Analysis)"),
        "spectral_artifact_score": (_FREQUENCY_INTERPRETATIONS, "### 📡 Signal 2: Frequency-Domain Analysis"),
        "temporal_inconsistency_score": (None, "### 🎬 Signal 3: Temporal Consistency (Video)"),
        "rppg_anomaly_score": (None, "### 💓 Signal 4: Biological Signal — rPPG"),
        "lip_sync_mismatch_score": (None, "### 🎙️ Signal 5: Audio-Visual Synchronisation"),
    }

    for ar in agent_results:
        signal = ar.get("signal_name", "")
        header = signal_interp.get(signal, (None, f"### {ar.get('agent_name', 'Agent')}"))[1]
        lines.append(header)
        lines.append("")

        score = ar.get("score", 0.5)
        conf = ar.get("confidence", 0.0)
        ran = ar.get("ran", True)
        weight = fusion_weights.get(signal, 0.0)
        direction = "FAKE-leaning" if score > 0.55 else ("REAL-leaning" if score < 0.45 else "Neutral")

        lines.append(f"**Score:** {score:.3f} | **Confidence:** {conf:.0%} | **Fusion Weight:** {weight:.1%} | **Signal Direction:** {direction}")
        lines.append("")

        if not ran:
            skipped_reason = ar.get("skipped_reason", "Not applicable.")
            if signal == "temporal_inconsistency_score":
                lines.append(rng.choice(_TEMPORAL_INTERPRETATIONS["skipped"]))
            elif signal == "rppg_anomaly_score":
                lines.append(rng.choice(_BIOLOGICAL_INTERPRETATIONS["skipped"]))
            elif signal == "lip_sync_mismatch_score":
                lines.append(rng.choice(_LIP_SYNC_INTERPRETATIONS["skipped"]))
            else:
                lines.append(f"*Skipped: {skipped_reason}*")
            lines.append("")
            continue

        details = ar.get("details", {})
        detail_note = details.get("note", "facial and background regions")

        if signal == "pixel_artifact_score":
            bucket = _get_score_bucket(score)
            templates = _SPATIAL_INTERPRETATIONS.get(bucket, _SPATIAL_INTERPRETATIONS["neutral"])
            txt = rng.choice(templates)
            lines.append(txt.replace("{detail_note}", str(detail_note)))
        elif signal == "spectral_artifact_score":
            bucket = _get_score_bucket(score)
            templates = _FREQUENCY_INTERPRETATIONS.get(bucket, _FREQUENCY_INTERPRETATIONS["neutral"])
            lines.append(rng.choice(templates))
        elif signal == "temporal_inconsistency_score":
            bucket = _get_temporal_bucket(ran, score)
            lines.append(rng.choice(_TEMPORAL_INTERPRETATIONS[bucket]))
        elif signal == "rppg_anomaly_score":
            bucket = _get_temporal_bucket(ran, score)
            lines.append(rng.choice(_BIOLOGICAL_INTERPRETATIONS[bucket]))
        elif signal == "lip_sync_mismatch_score":
            bucket = _get_temporal_bucket(ran, score)
            lines.append(rng.choice(_LIP_SYNC_INTERPRETATIONS[bucket]))
        else:
            lines.append(f"Score: {score:.3f}. No specialised interpretation available for this signal.")

        # Additional detail fields
        if details:
            notable = {k: v for k, v in details.items() if k not in ("note", "caveat", "error")}
            if notable:
                lines.append("")
                lines.append("*Technical measurements:*")
                for k, v in list(notable.items())[:5]:
                    lines.append(f"  - **{k.replace('_', ' ').title()}:** {v}")
            if "caveat" in details:
                lines.append("")
                lines.append(f"> ⚠️ **Caveat:** {details['caveat']}")

        lines.append("")

    return "\n".join(lines)


def _build_statistical_analysis(
    prob: float,
    conf: float,
    fusion_weights: dict,
    agent_results: list,
) -> str:
    active = [ar for ar in agent_results if ar.get("ran", True)]
    mean_agent_conf = sum(ar.get("confidence", 0) for ar in active) / max(len(active), 1)

    weight_table = "\n".join(
        f"| {s.replace('_score','').replace('_',' ').title()} | {w:.4f} | {w:.1%} |"
        for s, w in fusion_weights.items()
    )

    return f"""\
## STATISTICAL ANALYSIS

### Ensemble Fusion Results

| Metric | Value |
|---|---|
| Composite Deepfake Probability | **{prob:.4f}** ({prob:.1%}) |
| Verdict Confidence | **{conf:.4f}** ({conf:.0%}) |
| Active Agent Count | {len(active)} |
| Mean Agent Confidence | {mean_agent_conf:.1%} |

### Signal Weight Distribution

| Signal | Weight (raw) | Weight (%) |
|---|---|---|
{weight_table}

### Confidence Interpretation

{"⚠️ **Low confidence** — the system is uncertain and a human expert review is warranted." if conf < 0.40 else
 "✅ **Moderate confidence** — the verdict is grounded in consistent multi-signal evidence, though independent verification is advised." if conf < 0.70 else
 "🔵 **High confidence** — multiple independent signals strongly converge. This is a robust forensic finding."}

**Probability Interpretation:**
- Score > 0.75: High likelihood of synthetic origin
- Score 0.55–0.75: Probable synthetic content (LIKELY FAKE)
- Score 0.45–0.55: Inconclusive zone
- Score 0.25–0.45: Probable authentic content (LIKELY REAL)
- Score < 0.25: High likelihood of authentic origin

This sample scored **{prob:.3f}**, placing it in the **{
    'high-synthetic' if prob > 0.75 else
    'probable-synthetic' if prob > 0.55 else
    'inconclusive' if prob > 0.45 else
    'probable-authentic' if prob > 0.25 else
    'high-authentic'
} zone**.
"""


def _build_expert_opinion(
    verdict: str,
    prob: float,
    conf: float,
    media_type: str,
    rng: random.Random,
) -> str:
    if verdict == "LIKELY FAKE":
        stance = (
            f"It is this examiner's expert opinion that the submitted {media_type} exhibits "
            f"a pattern of forensic indicators that, taken together, provide a compelling case "
            f"for synthetic origin. The convergence of spatial, spectral{', temporal, and biological' if media_type == 'video' else ' '}"
            f"signals at a composite probability of {prob:.1%} — above the established threshold "
            f"for the LIKELY FAKE determination — supports this conclusion.\n\n"
            f"This finding should be considered in the context of the stated limitations below. "
            f"Independent corroboration by a human forensic examiner and, where possible, "
            f"access to the original, uncompressed source file is recommended before any "
            f"consequential determination is made."
        )
    elif verdict == "LIKELY REAL":
        stance = (
            f"It is this examiner's expert opinion that the submitted {media_type} does not "
            f"exhibit the forensic signatures characteristic of known synthetic generation methods "
            f"at the current detection sensitivity. The composite probability of {prob:.1%} places "
            f"the sample in the LIKELY REAL category with {conf:.0%} verdict confidence.\n\n"
            f"**This is not a certificate of authenticity.** Sophisticated adversarially-crafted "
            f"content, methods not represented in the training distribution, or generation techniques "
            f"released after this system's knowledge cutoff could evade detection. This finding "
            f"indicates absence of detected synthetic indicators — not confirmed authenticity."
        )
    else:
        stance = (
            f"The forensic evidence is inconclusive. Individual signals disagree and the composite "
            f"probability ({prob:.1%}) falls within the uncertainty band where neither synthetic nor "
            f"authentic determinations can be made with acceptable confidence ({conf:.0%}).\n\n"
            f"This examiner recommends: (1) acquisition of a higher-resolution or uncompressed "
            f"version of the sample; (2) manual review by a human expert; (3) supplementary analysis "
            f"using additional tools or methods not available in this pipeline. No action should be "
            f"taken based solely on this inconclusive finding."
        )

    return f"""\
## EXPERT OPINION

{stance}
"""


def _build_limitations() -> str:
    return """\
## LIMITATIONS AND CAVEATS

1. **Training distribution overfitting**: The spatial classifier was trained on specific deepfake datasets. 
   Generators not represented in the training data may produce outputs that evade detection.

2. **Compression sensitivity**: JPEG compression below quality 70 and H.264 encoding at high compression 
   ratios degrade frequency and spatial signals. Accuracy may be reduced for compressed media.

3. **Adversarial robustness**: A sophisticated actor who knows this system's detection signals 
   could craft inputs designed to evade them. This tool should not be the sole line of defence.

4. **No face detection guarantee**: If no face is detected, full-image analysis is performed — 
   which is less accurate than face-region-focused analysis.

5. **Quantum module**: The quantum-inspired weight optimisation runs as a classical simulation 
   (PennyLane, default.qubit backend). No quantum hardware is used and no quantum speedup is claimed.

6. **Diffusion model coverage**: Frequency analysis has been updated to target diffusion-model 
   artifacts (Corvi et al., 2023), but this remains an area of active research. Coverage of the 
   newest generation models (DALL-E 3, FLUX, SD3) is not fully validated.

7. **Legal admissibility**: This report is generated by an automated system and **is not intended 
   as legally admissible forensic evidence** without review by a certified human forensic examiner.
"""


def _build_recommendations(verdict: str) -> str:
    if verdict == "LIKELY FAKE":
        recs = [
            "Obtain the original, uncompressed source file for re-examination if possible.",
            "Cross-reference with blockchain/C2PA content provenance metadata if available.",
            "Submit for independent examination by a certified human digital forensics examiner.",
            "Document the full chain of custody for the media artifact.",
            "Do not publicly attribute or act on this finding without independent corroboration.",
        ]
    elif verdict == "LIKELY REAL":
        recs = [
            "Retain this report alongside the original media file for the record.",
            "Verify file metadata (EXIF, creation timestamps) for consistency.",
            "Note that this analysis cannot rule out sophisticated adversarial evasion.",
            "If consequential decisions depend on this determination, seek independent corroboration.",
        ]
    else:
        recs = [
            "Obtain a higher-resolution or uncompressed version of the sample for re-analysis.",
            "Commission independent expert review — this automated system cannot issue a reliable verdict.",
            "Do not make consequential decisions based on an inconclusive automated finding.",
            "Consider submitting the sample to additional detection pipelines for comparison.",
        ]

    recs_text = "\n".join(f"{i+1}. {r}" for i, r in enumerate(recs))
    return f"""\
## RECOMMENDATIONS

{recs_text}
"""


def _build_signature(case_id: str) -> str:
    now = datetime.now(timezone.utc)
    return f"""\
---

## REPORT CERTIFICATION

**System:** Obscuro Deepimage — Agentic Multi-Modal Deepfake Detection Framework  
**Version:** 1.0.0  
**Case Reference:** `{case_id}`  
**Report Generated:** {now.strftime('%Y-%m-%d %H:%M:%S UTC')}  

> *This report was generated automatically by the Obscuro Deepimage forensic AI system. 
> It is provided for research and investigative purposes only. The findings are probabilistic 
> and should not be treated as definitive legal proof without independent expert review. 
> Obscuro Deepimage accepts no liability for decisions made based solely on automated analysis.*

---
"""


# ─── Main entry point ─────────────────────────────────────────────────────────

def generate_forensic_report(
    verdict_dict: dict,
    filename: str = "unknown",
    input_hash: str = "",
) -> str:
    """
    Generate a full forensic specialist report from a verdict dict.

    Args:
        verdict_dict: The ForensicVerdict as a dict (from .model_dump())
        filename: Original filename of the analysed media
        input_hash: Hash of the input file for case ID generation

    Returns:
        Markdown-formatted forensic report string.
    """
    rng = random.Random(input_hash or filename)  # seeded for reproducibility per case

    verdict = verdict_dict.get("verdict", "UNCERTAIN")
    prob = verdict_dict.get("deepfake_probability", 0.5)
    conf = verdict_dict.get("confidence_in_verdict", 0.0)
    media_type = verdict_dict.get("media_type", "image")
    agent_results = verdict_dict.get("agent_results", [])
    fusion_weights = verdict_dict.get("fusion_weights", {})

    case_id = _make_case_id(input_hash)

    sections = [
        f"# 🔍 DIGITAL FORENSIC EXAMINATION REPORT\n",
        f"---\n",
        _build_executive_summary(verdict, prob, conf, media_type, case_id, filename, rng),
        _build_methodology(),
        _build_signal_findings(agent_results, fusion_weights, rng),
        _build_statistical_analysis(prob, conf, fusion_weights, agent_results),
        _build_expert_opinion(verdict, prob, conf, media_type, rng),
        _build_limitations(),
        _build_recommendations(verdict),
        _build_signature(case_id),
    ]

    return "\n\n".join(sections)
