"""
Frequency Analysis Agent — Obscuro Deepimage.

Deep generative models (GANs and diffusion models) leave characteristic
spectral fingerprints absent from real photographs.

Methods implemented:
  1. FFT magnitude spectrum analysis — GAN upsampling grid artifacts
  2. DCT coefficient distribution — JPEG quantisation forensics
  3. Diffusion-model channel cross-correlation (Corvi et al., ICASSP 2023)
  4. SRM-inspired noise residual analysis — camera vs. synthetic noise floor
  5. High-frequency energy ratio — diffusion models suppress HF differently than GANs

References:
  - Frank et al., "Leveraging Frequency Analysis for Deep Fake Image Recognition",
    ICML 2020.
  - Corvi et al., "On the Detection of Synthetic Images Generated by Diffusion Models",
    ICASSP 2023.
  - Fridrich & Kodovsky, "Rich Models for Steganalysis of Digital Images" (SRM), 2012.
"""
import logging
import numpy as np
import cv2
from typing import Dict, Any, Tuple

from app.schemas import AgentResult

logger = logging.getLogger(__name__)


# ── FFT spectrum analysis ──────────────────────────────────────────────────────

def _fft_analysis(image_bgr: np.ndarray) -> Tuple[float, Dict[str, float]]:
    """
    Compute FFT-based spectral anomaly score.
    GAN upsampling leaves periodic spectral peaks and anomalous HF/LF ratios.
    Returns (score_0_to_1, detail_dict). Higher = more spectrally anomalous.
    """
    gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY).astype(np.float32)
    h, w = gray.shape

    # Hann windowing to reduce spectral leakage
    window = np.outer(np.hanning(h), np.hanning(w)).astype(np.float32)
    fft = np.fft.fft2(gray * window)
    fft_shift = np.fft.fftshift(fft)
    magnitude = np.log1p(np.abs(fft_shift))

    cy, cx = h // 2, w // 2
    y_grid, x_grid = np.ogrid[:h, :w]
    dist = np.sqrt((y_grid - cy) ** 2 + (x_grid - cx) ** 2)

    # Low-freq vs high-freq energy
    lf_mask = dist <= min(h, w) // 8
    hf_mask = dist > min(h, w) // 3
    lf_energy = float(magnitude[lf_mask].mean())
    hf_energy = float(magnitude[hf_mask].mean())
    hf_ratio = hf_energy / (lf_energy + 1e-6)

    # Periodic GAN grid peaks in top 0.5% of spectrum
    top_pct = float(np.percentile(magnitude, 99.5))
    peak_pixels = int((magnitude > top_pct).sum())
    expected = max(1.0, h * w * 0.005)
    peak_anomaly = float(peak_pixels / expected)

    # Azimuthal variance: GANs often have directional upsampling structure
    angles = np.arctan2(y_grid - cy, x_grid - cx)
    bins = np.digitize(angles, np.linspace(-np.pi, np.pi, 17)) - 1
    az_energies = [float(magnitude[bins == i].mean()) for i in range(16)]
    az_variance = float(np.std(az_energies) / (np.mean(az_energies) + 1e-6))

    hf_score    = float(np.clip((hf_ratio    - 0.15) / 0.25, 0.0, 1.0))
    peak_score  = float(np.clip((peak_anomaly - 1.0)  / 2.0,  0.0, 1.0))
    az_score    = float(np.clip((az_variance  - 0.10) / 0.20, 0.0, 1.0))
    combined    = 0.40 * hf_score + 0.35 * peak_score + 0.25 * az_score

    return float(np.clip(combined, 0.0, 1.0)), {
        "hf_lf_ratio":         round(hf_ratio,    4),
        "hf_anomaly_score":    round(hf_score,    4),
        "spectral_peak_score": round(peak_score,  4),
        "azimuthal_var_score": round(az_score,    4),
    }


# ── DCT analysis ───────────────────────────────────────────────────────────────

def _dct_analysis(image_bgr: np.ndarray) -> Tuple[float, float]:
    """
    DCT block coefficient distribution analysis.
    Real JPEG images have Laplacian-distributed AC coefficients with quantisation steps.
    AI-generated images often have a smoother (lower kurtosis) distribution.
    Returns (score, confidence). Higher score = more likely synthetic.
    """
    gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY).astype(np.float32)
    h, w = gray.shape
    coeffs = []
    for y in range(0, h - 8, 8):
        for x in range(0, w - 8, 8):
            block = gray[y:y + 8, x:x + 8]
            dct_block = cv2.dct(block)
            coeffs.extend(dct_block.flatten()[1:].tolist())   # exclude DC

    if len(coeffs) < 100:
        return 0.5, 0.2

    coeffs = np.array(coeffs, dtype=np.float32)
    kurtosis = float(
        np.mean((coeffs - coeffs.mean()) ** 4)
        / (coeffs.std() ** 4 + 1e-6)
    )
    # Real JPEG kurtosis typically 8–25; synthetic 3–7
    score      = float(np.clip(1.0 - (kurtosis - 3.0) / 25.0, 0.0, 1.0))
    confidence = float(np.clip(abs(kurtosis - 8.0) / 15.0, 0.10, 0.75))
    return score, confidence


# ── Diffusion-model channel cross-correlation ──────────────────────────────────

def _diffusion_channel_score(image_bgr: np.ndarray) -> float:
    """
    Diffusion models apply noise across all channels uniformly, yielding
    unusually high RGB cross-correlation in the residual domain.
    Corvi et al. (ICASSP 2023) validates this signal.
    Returns score in [0,1]; higher = more diffusion-like.
    """
    b, g, r = cv2.split(image_bgr.astype(np.float32))

    # Work on residual (high-pass) to isolate noise floor
    def residual(ch: np.ndarray) -> np.ndarray:
        blur = cv2.GaussianBlur(ch, (5, 5), 0)
        res  = ch - blur
        return (res - res.mean()) / (res.std() + 1e-6)

    b_r, g_r, r_r = residual(b), residual(g), residual(r)
    bg = float(np.mean(b_r * g_r))
    br = float(np.mean(b_r * r_r))
    gr = float(np.mean(g_r * r_r))
    avg_corr = (bg + br + gr) / 3.0

    # Natural images: cross-corr ~0.3–0.7; diffusion: >0.85
    return float(np.clip((avg_corr - 0.65) / 0.25, 0.0, 1.0))


# ── SRM-inspired noise residual analysis ──────────────────────────────────────

def _srm_noise_analysis(image_bgr: np.ndarray) -> Tuple[float, Dict[str, float]]:
    """
    Steganalysis Rich Model (SRM)-inspired approach:
    Apply a set of high-pass "noise extraction" filters, then analyse the
    resulting residual's statistical moments.

    Real cameras:    non-Gaussian residual with sensor-noise structure
    AI generators:  residual is near-Gaussian (too clean) OR has structured
                    periodic noise from the denoising U-Net

    Returns (score, details). Higher score = more likely synthetic.
    """
    gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY).astype(np.float32)

    # SRM filter bank (three simple high-pass kernels)
    k1 = np.array([[-1, 2, -1]], dtype=np.float32) / 2.0          # horizontal
    k2 = np.array([[-1], [2], [-1]], dtype=np.float32) / 2.0      # vertical
    k3 = np.array([[0, -1, 0], [-1, 4, -1], [0, -1, 0]],
                  dtype=np.float32) / 4.0                           # Laplacian

    residuals = [
        cv2.filter2D(gray, -1, k1),
        cv2.filter2D(gray, -1, k2),
        cv2.filter2D(gray, -1, k3),
    ]

    details: Dict[str, float] = {}
    scores = []

    for i, res in enumerate(residuals):
        flat = res.flatten()
        mean = float(np.mean(flat))
        std  = float(np.std(flat)) + 1e-6

        # Kurtosis: real cameras ~3–6, AI can be <3 (too Gaussian) or >8 (periodic)
        kurt = float(np.mean(((flat - mean) / std) ** 4))
        # Distance from natural camera range [3, 6]
        kurt_score = float(np.clip(abs(kurt - 4.5) / 4.5, 0.0, 1.0))

        # Skewness: real noise is roughly symmetric; strong skew is suspicious
        skew = float(np.mean(((flat - mean) / std) ** 3))
        skew_score = float(np.clip(abs(skew) / 1.5, 0.0, 1.0))

        combined = 0.6 * kurt_score + 0.4 * skew_score
        scores.append(combined)
        details[f"srm_filter{i+1}_kurt"] = round(kurt, 3)
        details[f"srm_filter{i+1}_score"] = round(combined, 4)

    srm_score = float(np.mean(scores))
    return float(np.clip(srm_score, 0.0, 1.0)), details


# ── Public run function ────────────────────────────────────────────────────────

def run(image_bgr: np.ndarray) -> AgentResult:
    """Run all frequency-domain analyses on a BGR image."""
    try:
        fft_score,  fft_details  = _fft_analysis(image_bgr)
        dct_score,  dct_conf     = _dct_analysis(image_bgr)
        diff_score               = _diffusion_channel_score(image_bgr)
        srm_score,  srm_details  = _srm_noise_analysis(image_bgr)

        # Ensemble: FFT + DCT + diffusion channel + SRM
        final_score = (
            0.35 * fft_score
            + 0.25 * dct_score
            + 0.20 * diff_score
            + 0.20 * srm_score
        )
        # Confidence: frequency analysis is moderately reliable; SRM adds robustness
        final_conf = min(0.72, 0.50 + 0.22 * (dct_conf / 0.75))

        details = {
            **fft_details,
            **srm_details,
            "dct_kurtosis_score":    round(dct_score,  4),
            "dct_confidence":        round(dct_conf,   4),
            "diffusion_ch_score":    round(diff_score, 4),
            "srm_noise_score":       round(srm_score,  4),
            "method": (
                "FFT spectral peaks + DCT kurtosis + "
                "diffusion channel cross-correlation + SRM noise residual"
            ),
            "note": (
                "Frequency analysis calibrated for GAN upsampling and diffusion-model artifacts. "
                "Reliability reduced on heavily compressed (JPEG q<70) images."
            ),
        }

        return AgentResult(
            agent_name="FrequencyAnalysisAgent",
            signal_name="spectral_artifact_score",
            score=float(np.clip(final_score, 0.0, 1.0)),
            confidence=float(np.clip(final_conf, 0.0, 1.0)),
            details=details,
        )

    except Exception as exc:
        logger.error("FrequencyAnalysisAgent error: %s", exc, exc_info=True)
        return AgentResult(
            agent_name="FrequencyAnalysisAgent",
            signal_name="spectral_artifact_score",
            score=0.5,
            confidence=0.1,
            details={"error": str(exc)},
        )
