kind = "api"
previewPath = "/"
title = "Obscuro Deepimage"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8000
name = "Deepimage"
paths = ["/"]

[services.development]
run = "cd /home/runner/workspace/deepfake-detector && uv run python start_api.py"
